// Generated by https://quicktype.io

export interface IProductResponse {
  data: IProduct[];
}

export interface IProduct {
  id:          number;
  name:        string;
  price:       number;
  image:       string;
  available?:   number;
  category_id: number;
  created_at?:  string;
  updated_at?:  string;
}
